version: '3.4'

volumes:
  prometheus_data: { }
  grafana_data: { }

services:
  db:
    image: mysql:8.0
    container_name: wex_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: felpeto
      MYSQL_DATABASE: wex
      MYSQL_USER: murilo
    ports:
      - 3306:3306
  flyway:
    image: flyway/flyway:7.5.2
    container_name: wex_flyway
    command: -url=jdbc:mysql://db -schemas=wex -user=root -password=admin -connectRetries=60 migrate
    volumes:
      - ../resources/flyway/db:/flyway/sql
    depends_on:
      - db
  adminer:
    image: adminer:4.8.1
    container_name: wex_adminer
    restart: always
    ports:
      - 8111:8080
  swagger-ui:
    image: mrin9/rapidoc
    container_name: wex_swagger
    environment:
      SPEC_URL: http://localhost:5000/v1/openapi
      RAPIDOC_OPTIONS: "theme='dark' allow-authentication='true' api-key-name='Authorization' api-key-value='Bearer XPTO' api-key-location='header' "
    ports:
      - 8112:80
  nginx:
    container_name: wex_nginx
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      NGINX_PORT: 5000
      NGINX_HOST: 127.0.0.1
    network_mode: host
    expose:
      - 5000
  prometheus:
    container_name: wex_prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=/prometheus/'
      - '--web.route-prefix=/'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    restart: always
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
  grafana:
    container_name: wex_grafana
    image: grafana/grafana-oss:8.2.4
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: unless-stopped
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
    expose:
      - 3000
  keycloak:
    container_name: wex_keycloak
    image: quay.io/keycloak/keycloak:22.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev --import-realm
    volumes:
      - ./keycloak/wex-realm.json:/opt/keycloak/data/import/wex-realm.json
    ports:
      - '8081:8080'
